language: node_js

node_js:
  - "6"
  - "8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

sudo: false

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export NODE_ENV=development

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run test
  - npm run test-node

env:
  - CXX=g++-4.8